//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricityBoardApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ElectricityBoardDatabaseEntities : DbContext
    {
        public ElectricityBoardDatabaseEntities()
            : base("name=ElectricityBoardDatabaseEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBillHistory> tblBillHistories { get; set; }
        public virtual DbSet<tblConsumer> tblConsumers { get; set; }
        public virtual DbSet<vPaymentDetail> vPaymentDetails { get; set; }
        public virtual DbSet<vUnitsConsumption> vUnitsConsumptions { get; set; }
        public virtual DbSet<tblLogin> tblLogins { get; set; }
    }
}
